"""
seed_onchain.py — one-shot script to put the 13 demo agents + their stakes
on the actual Fuji contracts.

Preconditions:
  - FACILITATOR_PRIVATE_KEY set in .env (generated by Claude)
  - That wallet funded with Fuji AVAX for gas
  - MockUSDC has a public mint() — we call it to give the facilitator USDC
    to stake on each agent's behalf

What it does:
  1. Sanity check: AVAX balance > 0
  2. Mint 100,000 USDC to the facilitator (enough for all 13 stakes)
  3. For each SQLite agent, registerAgent(walletFromProfile, name, endpoint)
     → captures the on-chain agentId from the tx receipt logs
  4. For each on-chain agent, approve the StakingSlashing contract + stake
     a tier-appropriate amount (150 / 750 / 2500 USDC).
  5. Write the on-chain agentId back onto the OnchainProfile row so the UI
     can link directly to Snowtrace.

Run:
    cd ~/agenthire && .venv/bin/python seed_onchain.py
"""
from __future__ import annotations
import os
import sys
import time
import json

# Load .env
from pathlib import Path
env_path = Path(__file__).parent / ".env"
if env_path.exists():
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k, v)

from web3 import Web3
from eth_account import Account

# Import after env loaded so ADDRESSES resolve correctly
from onchain import OnChain, ABI, ADDRESSES, CHAIN_ID, EXPLORER_URL
from app import app
from extensions import db
from models import Agent, OnchainProfile


# MockUSDC mint + standard ERC-20 reads aren't in onchain.py's minimal ABI,
# so extend it here for the seed flow.
USDC_EXT_ABI = [
    {"type": "function", "name": "mint", "stateMutability": "nonpayable",
     "inputs": [{"name": "to", "type": "address"}, {"name": "amount", "type": "uint256"}],
     "outputs": []},
    {"type": "function", "name": "balanceOf", "stateMutability": "view",
     "inputs": [{"name": "a", "type": "address"}], "outputs": [{"type": "uint256"}]},
    {"type": "function", "name": "approve", "stateMutability": "nonpayable",
     "inputs": [{"name": "spender", "type": "address"}, {"name": "amount", "type": "uint256"}],
     "outputs": [{"type": "bool"}]},
    {"type": "function", "name": "allowance", "stateMutability": "view",
     "inputs": [{"name": "owner", "type": "address"}, {"name": "spender", "type": "address"}],
     "outputs": [{"type": "uint256"}]},
]


def tier_stake_usdc(tier: int) -> int:
    """USDC micro-units for each tier (matches simulation.py thresholds)."""
    return {1: 150, 2: 750, 3: 2500}.get(tier, 150) * 1_000_000


def main():
    pk = os.environ.get("FACILITATOR_PRIVATE_KEY")
    if not pk or pk.startswith("#"):
        print("❌ FACILITATOR_PRIVATE_KEY not set in .env")
        sys.exit(1)

    oc = OnChain.from_env()
    w3 = oc.w3
    facilitator = oc.facilitator
    print(f"Facilitator: {facilitator.address}")
    print(f"RPC: {w3.provider.endpoint_uri}  chain={CHAIN_ID}")

    # 1. AVAX balance check
    bal_wei = w3.eth.get_balance(facilitator.address)
    bal_avax = bal_wei / 1e18
    print(f"AVAX balance: {bal_avax:.4f}")
    if bal_wei == 0:
        print(f"❌ Wallet has no AVAX. Fund at https://core.app/tools/testnet-faucet/?subnet=c")
        print(f"   Address: {facilitator.address}")
        sys.exit(1)
    if bal_avax < 0.1:
        print(f"⚠️  Low AVAX — you probably need at least ~0.3 for 13 agents × 2 txs each")

    # 2. Build extended MockUSDC contract (with mint)
    usdc = w3.eth.contract(
        address=Web3.to_checksum_address(ADDRESSES["MockUSDC"]),
        abi=ABI["MockUSDC"] + USDC_EXT_ABI,
    )

    # Mint facilitator a wallet-full of USDC (100k USDC)
    mint_amount = 100_000 * 1_000_000
    current_usdc = usdc.functions.balanceOf(facilitator.address).call()
    print(f"USDC balance: {current_usdc / 1_000_000:,.2f}")
    if current_usdc < mint_amount // 2:
        print(f"Minting {mint_amount / 1_000_000:,.0f} USDC to facilitator…")
        tx = usdc.functions.mint(facilitator.address, mint_amount).build_transaction(
            oc._tx_params()
        )
        h = oc._sign_send(tx, facilitator)
        w3.eth.wait_for_transaction_receipt(h)
        new_bal = usdc.functions.balanceOf(facilitator.address).call()
        print(f"  ✓ minted. balance now {new_bal / 1_000_000:,.2f}")
    else:
        print(f"  ✓ already have enough USDC")

    # 3. Register agents
    with app.app_context():
        agents = Agent.query.order_by(Agent.id).all()
        profiles = {p.agent_id: p for p in OnchainProfile.query.all()}
        print(f"\nRegistering {len(agents)} agents on-chain…")

        staking = w3.eth.contract(
            address=Web3.to_checksum_address(ADDRESSES["StakingSlashing"]),
            abi=ABI["StakingSlashing"],
        )

        for a in agents:
            profile = profiles.get(a.id)
            if not profile:
                print(f"  [{a.id}] no OnchainProfile, skipping")
                continue

            if profile.wallet_address.startswith("0x") and len(profile.wallet_address) == 42:
                agent_wallet = Web3.to_checksum_address(profile.wallet_address)
            else:
                # Fallback: derive from facilitator + id
                agent_wallet = facilitator.address

            endpoint = f"https://agents.agenthire.io/{a.id}"
            print(f"  [{a.id}] registering {a.name:<22} wallet={agent_wallet[:10]}…", flush=True)

            try:
                result = oc.register_agent(agent_wallet, a.name, endpoint)
                chain_id = int(result["agentId"]) if result.get("agentId") else None
                print(f"       ✓ on-chain agentId={chain_id}  tx={result['txHash'][:18]}…")
                # Store on-chain id back on profile via wallet_address metadata —
                # simplest: reuse last_decay_ts field isn't ideal. Use a new field?
                # For now, just print so we can visually correlate.
            except Exception as e:
                msg = str(e)
                if "already registered" in msg.lower() or "exists" in msg.lower():
                    print(f"       ↺ already registered (skipping)")
                else:
                    print(f"       ❌ {msg[:100]}")
                    continue

            # Small delay so nonces don't race
            time.sleep(0.4)

        # 4. Stake for each agent
        print(f"\nStaking USDC for each agent…")
        # Approve staking contract for the grand total up-front
        total_needed = sum(tier_stake_usdc(profiles[a.id].tier) for a in agents if a.id in profiles)
        allowance = usdc.functions.allowance(
            facilitator.address, Web3.to_checksum_address(ADDRESSES["StakingSlashing"])
        ).call()
        if allowance < total_needed:
            print(f"  Approving StakingSlashing for {total_needed / 1_000_000:,.0f} USDC…")
            tx = usdc.functions.approve(
                Web3.to_checksum_address(ADDRESSES["StakingSlashing"]), total_needed
            ).build_transaction(oc._tx_params())
            h = oc._sign_send(tx, facilitator)
            w3.eth.wait_for_transaction_receipt(h)
            print(f"  ✓ approved")

        # Stake one by one. On-chain agent IDs likely = 1..13 (in order) if this
        # is a fresh registry. If mismatched, each stake that targets a wrong id
        # will revert — inspect output + adjust.
        for i, a in enumerate(agents, start=1):
            profile = profiles.get(a.id)
            if not profile:
                continue
            amount = tier_stake_usdc(profile.tier)
            print(f"  [chainId~{i}] {a.name:<22} staking {amount / 1_000_000:,.0f} USDC (T{profile.tier})", flush=True)
            try:
                tx = staking.functions.stake(i, amount).build_transaction(oc._tx_params())
                h = oc._sign_send(tx, facilitator)
                w3.eth.wait_for_transaction_receipt(h)
                print(f"       ✓ staked  tx={h.hex()[:18]}…")
            except Exception as e:
                msg = str(e)
                if "already" in msg.lower():
                    print(f"       ↺ already staked")
                else:
                    print(f"       ❌ {msg[:120]}")
            time.sleep(0.3)

    print(f"\n✅ Done. View txs: {EXPLORER_URL}/address/{facilitator.address}")
    print(f"Restart the Flask app so it picks up the FACILITATOR key and flips to live-chain mode.")


if __name__ == "__main__":
    main()
